import clsx from "clsx";
import type { Metadata } from "next";
import { Noto_Serif, Rubik, Fira_Code } from "next/font/google";
import Link from "next/link";

import "./globals.css";

const rubik = Rubik({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-rubik",
  fallback: ["sans-serif"],
});

const notoSans = Noto_Serif({
  subsets: ["latin"],
  variable: "--font-noto-serif",
  fallback: ["sans-serif"],
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-fira-code",
  fallback: ["monospace"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "antialiased",
          "font-sans",
          "dark:bg-zinc-950",
          "dark:text-neutral-200",
          rubik.variable,
          notoSans.variable,
        )}
      >
        <div className="mx-auto container px-6 max-w-2xl md:px-0 py-12 md:py-24">
          <header className="mb-12">
            <nav className="font-sans">
              <ul className="flex gap-4">
                <li>
                  <Link className="text-base" href="/">
                    about me
                  </Link>
                </li>
                <li>
                  <Link className="text-base" href="/blog">
                    blog
                  </Link>
                </li>
              </ul>
            </nav>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
